### ISSUE TITLE
Export as pandas dataframe

### ISSUE THREAD

**Issue by dmfigol** [dmfigol/simple-smartsheet#22]
Request from @cmlccie

Will probably need to add pandas dependency as extras

**Comment by cmlccie** [comment]
Yes, I wouldn't add it as a primary dependency, but adding it as an extra would be good.  Those who want to load SmartSheets into DataFrames probably already have pandas installed and in-use in their projects, but when spinning-up a quick script to work with a SmartSheet, it would be nice to simply install simple-smartsheet with the pandas extra.

**Comment by dmfigol** [comment]
@cmlccie should be part of the next release (0.5.0), meanwhile available on master.

**Comment by cmlccie** [comment]
Awesome!  Thank you @dmfigol.

**Comment by dmfigol** [comment]
@cmlccie 0.5.0 (with this feature) is now available on pypi
